[package]
name = "smve_render"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bevy_app = "0.14"
bevy_ecs = "0.14"
bevy_render = "0.14"
bytemuck = "1.17"
bevy_math = "0.14"
bevy_asset = "0.14"
bevy_core_pipeline = "0.14"
